name: xsar
channels:
  - conda-forge
dependencies:
  - aiohttp
  - cartopy >=0.19.0
  - dask >=2021.6.2
  - gdal >=3.3
  - geopandas
  - more-itertools
  - rasterio >=1.2.6
  - setuptools_scm
  - setuptools_scm_git_archive
  - xarray
  - rioxarray >=0.10
  - pandoc
  - python
  - importlib_resources
  - lxml