name: xsar-tests
channels:
  - conda-forge
dependencies:
  - ipython
  - python
  - pre-commit
  - pytest
  - pytest-reportlog
  - pytest-cov
  - numpy
  - toolz
  - cytoolz
  - python-dateutil
  - construct
  - fsspec
  - xarray
  - dask
  - distributed
  - aiohttp
  - rasterio
  - cartopy
  - pyproj
  - scipy
  - shapely
  - geopandas
  - lxml
  - rioxarray
  - mapraster
  - safe_s1
  - xradarsat2
  - safe_rcm
