name: xsar-tests
channels:
  - conda-forge
dependencies:
  - ipython
  - python
  - pre-commit
  - pytest
  - pytest-reportlog
  - pytest-cov
  - numpy
  - toolz
  - cytoolz
  - python-dateutil
  - construct
  - fsspec
  - xarray
  - dask
  - distributed
  - aiohttp
  - rasterio
  - cartopy
  - pyproj
  - scipy
  - shapely
  - geopandas
  - lxml
  - rioxarray
  - mapraster
  - xmlschema <4.0.0
  - xarray-safe-s1
  - xradarsat2
  - xarray-safe-rcm
